version: '3.1'

services:

  db:
    image: beapen/ctdict
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass

  ctakes:
    image: beapen/qtakes
    restart: unless-stopped
    ports:
      - 8093:8080
    environment:
      MYSQL_ROOT_PASSWORD: pass
      ctakes.umls_apikey: <MY-KEY-HERE>
    depends_on:
      - db